<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU</Platforms>
    <AssemblyName>App Keeper</AssemblyName>
    <RootNamespace>AppKeeper</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\appkeeper.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Assets\appkeeper.svg" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <Page Remove="Tests\**\*.xaml" />
    <None Remove="Tests\**\*" />
  </ItemGroup>
</Project>
